#!/usr/bin/env -S deno run -A
// Vendors the minimal @ebay/skin (https://github.com/eBay/skin) compiled CSS
// that the eBay-Pricing demo (/demos/ebay-pricing) needs into
//   apps/shell/static/vendor/ebay-skin/ebay-skin.css
// as one self-contained bundle, so the demo works offline and carries no CDN
// dependency — matching the repo's static-asset convention. Skin is MIT.
//
// The ONE external reference is Market Sans (eBay's brand webfont): Skin's
// marketsans.css @font-face points at eBay's own font CDN. We keep that
// reference rather than redistribute the proprietary font — offline it simply
// falls back to Arial (font-display: swap), so the page stays fully functional.
//
// Skin's compiled `dist/**` leaves are self-contained (no @import; they only
// reference token custom properties), so they can be concatenated safely.
//
// Theme handling: Skin ships light tokens at :root and dark tokens behind
// `@media (prefers-color-scheme: dark)`, so the bundle is theme-aware out of the
// box. On top of that we generate a manual override — the same token bodies
// re-scoped under `:root[data-skin-theme="light"|"dark"]` — so the demo's
// Auto/Light/Dark switch can force a theme regardless of the OS setting. With no
// data-skin-theme attribute (Auto), the built-in media query governs.
//
// Re-run to upgrade Skin: bump VERSION below, then `deno task vendor:ebay-skin`.

const VERSION = "19.28.0";
const BASE = `https://unpkg.com/@ebay/skin@${VERSION}`;

const OUT_DIR = new URL(
  "../apps/shell/static/vendor/ebay-skin/",
  import.meta.url,
);

// Token layers (order matters: core primitives → light semantic → dark semantic).
const TOKENS = {
  core: "dist/tokens/evo-core.css",
  light: "dist/tokens/evo-light.css",
  dark: "dist/tokens/evo-dark.css",
};

// Component leaves the demo actually uses, in cascade order.
const COMPONENTS = [
  "dist/global/global.css", // base reset: body bg/fg/font, a, fieldset/legend
  "dist/typography/typography.css",
  "dist/button/button.css",
  "dist/textbox/textbox.css",
  "dist/field/field.css",
  "dist/segmented-buttons/segmented-buttons.css",
  "dist/listbox/listbox.css",
  "dist/marketsans/marketsans.css", // @font-face → eBay CDN (graceful fallback)
];

async function fetchCss(path: string): Promise<string> {
  const url = `${BASE}/${path}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`GET ${url} → HTTP ${res.status}`);
  return await res.text();
}

// Return the declarations inside the first `:root { ... }` block, brace-matched.
// evo-light.css is a lone `:root {}`; evo-dark.css wraps one in an @media — in
// both cases the first `:root` block holds the semantic tokens we want.
function extractRootInner(css: string): string {
  const at = css.indexOf(":root");
  if (at < 0) throw new Error("no :root block found");
  const open = css.indexOf("{", at);
  if (open < 0) throw new Error("no { after :root");
  let depth = 0;
  for (let i = open; i < css.length; i++) {
    const c = css[i];
    if (c === "{") depth++;
    else if (c === "}") {
      depth--;
      if (depth === 0) return css.slice(open + 1, i).trim();
    }
  }
  throw new Error("unbalanced braces in :root block");
}

// Re-scope a :root token body under a data-skin-theme selector (manual override).
function scopeTheme(inner: string, theme: "light" | "dark"): string {
  const indented = inner
    .split("\n")
    .map((l) => (l.trim() ? "    " + l : l))
    .join("\n");
  return `:root[data-skin-theme="${theme}"] {\n${indented}\n}`;
}

console.log(`Vendoring @ebay/skin@${VERSION} …`);

const core = await fetchCss(TOKENS.core);
const light = await fetchCss(TOKENS.light);
const dark = await fetchCss(TOKENS.dark);
const lightInner = extractRootInner(light);
const darkInner = extractRootInner(dark);

const componentCss: string[] = [];
for (const path of COMPONENTS) {
  console.log(`  · ${path}`);
  componentCss.push(
    `/* ── @ebay/skin/${
      path.replace(/^dist\//, "").replace(/\/[^/]+$/, "")
    } ──────────────────────────────── */\n` +
      (await fetchCss(path)).trim(),
  );
}

const header = `/*!
 * eBay Skin (vendored) — https://github.com/eBay/skin  ·  @ebay/skin@${VERSION}  ·  MIT
 *
 * Generated by scripts/vendor-ebay-skin.ts — DO NOT EDIT BY HAND.
 * Minimal compiled bundle for the eBay-Pricing demo (/demos/ebay-pricing):
 * design tokens (Evo), base reset, typography, button, textbox, field,
 * segmented-buttons, listbox, and the Market Sans @font-face.
 *
 * Theme: light tokens at :root, dark tokens under @media(prefers-color-scheme:
 * dark) — plus manual :root[data-skin-theme="light"|"dark"] overrides for the
 * demo's Auto/Light/Dark switch. Market Sans loads from eBay's CDN and falls
 * back to Arial offline.
 */`;

const bundle = [
  header,
  `/* ── tokens: core palette primitives ──────────────────────────────── */\n${core.trim()}`,
  `/* ── tokens: semantic — light (default, :root) ────────────────────── */\n${light.trim()}`,
  `/* ── tokens: semantic — dark (auto, @media prefers-color-scheme) ──── */\n${dark.trim()}`,
  `/* ── tokens: manual theme overrides (data-skin-theme) ─────────────── */\n${
    scopeTheme(lightInner, "light")
  }\n${scopeTheme(darkInner, "dark")}`,
  ...componentCss,
  "",
].join("\n\n");

await Deno.mkdir(OUT_DIR, { recursive: true });
await Deno.writeTextFile(new URL("ebay-skin.css", OUT_DIR), bundle);

const readme = `# eBay Skin (vendored)

Minimal compiled CSS from [@ebay/skin](https://github.com/eBay/skin)
(\`@ebay/skin@${VERSION}\`, MIT), bundled for the eBay-Pricing demo at
\`/demos/ebay-pricing\`.

- **Do not edit \`ebay-skin.css\` by hand.** It is generated. To change the set of
  components or upgrade Skin, edit \`scripts/vendor-ebay-skin.ts\` and run
  \`deno task vendor:ebay-skin\`.
- Bundled: Evo design tokens (core + light + dark), base reset, typography,
  button, textbox, field, segmented-buttons, listbox, and the Market Sans
  \`@font-face\`.
- **Market Sans** is referenced from eBay's font CDN (\`ir.ebaystatic.com\`), the
  only external dependency. Offline it falls back to Arial via
  \`font-display: swap\`; the page stays fully functional. We reference rather
  than redistribute it because the font is eBay's proprietary brand asset (not
  covered by Skin's MIT license).
- Theme: light at \`:root\`, dark under \`@media (prefers-color-scheme: dark)\`,
  with manual \`:root[data-skin-theme="light"|"dark"]\` overrides driving the
  demo's Auto/Light/Dark switch.
`;
await Deno.writeTextFile(new URL("README.md", OUT_DIR), readme);

const bytes = new TextEncoder().encode(bundle).length;
console.log(
  `\n✓ wrote apps/shell/static/vendor/ebay-skin/ebay-skin.css (${
    (bytes / 1024).toFixed(1)
  } KB) + README.md`,
);
